logging:
  level:
    com.vhausler.property.stats: debug
server:
  port: 8080
spring:
  task:
    scheduling:
      pool:
        size: 1
  application:
    name: property-stats
#  datasource:
#    url: jdbc:postgresql://localhost:5432/property_stats?currentSchema=property_stats&gssEncMode=disable
#    username: postgres
#    password: admin
  jpa:
    show-sql: false
    properties:
      hibernate:
        id:
          new_generator_mappings: false
        show_sql: false
        format_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.xml
    url: jdbc:postgresql://localhost:5432/property_stats?currentSchema=property_stats&gssEncMode=disable
    default-schema: property_stats
    user: postgres
    password: admin
  main:
    allow-circular-references: true
property-stats:
  webdriver:
    headless: true
    pathToFirefoxExecutable: 'C:\Program Files\Mozilla Firefox\firefox.exe'
  headersThreadCount: 1
  paramsThreadCount: 1
  batchSize: 15000
  maintenanceBatchSize: 1500000