logging:
  level:
    com.vhausler.property.stats: debug
server:
  port: 8080
spring:
  task:
    scheduling:
      pool:
        size: 3
  application:
    name: property-stats
  datasource:
    url: jdbc:postgresql://localhost:5432/property_stats?currentSchema=property_stats&gssEncMode=disable
    username: postgres
    password: admin
  jpa:
    show-sql: false
    properties:
      hibernate:
        id:
          new_generator_mappings: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.xml
    url: jdbc:postgresql://localhost:5432/property_stats?currentSchema=property_stats&gssEncMode=disable
    default-schema: property_stats
    user: postgres
    password: admin
property-stats:
  webdriver:
    headless: true
    pathToFirefoxExecutable: 'C:\Program Files\Mozilla Firefox\firefox.exe'