package com.vhausler.property.stats.model.dto;

public enum MaintenanceEnum {
    PRICE_MAINTENANCE, PRICE_PER_SQUARE_METER_AND_SQUARE_METERS_MAINTENANCE, SCRAPER_RESULT_DUPLICATES_MAINTENANCE, PARAMS_DONE
}
